extends:
  - stylelint-config-standard
  - stylelint-config-recess-order
  - stylelint-rscss/config
plugins:
  - stylelint-scss
rules:
  string-quotes: single
  no-empty-source: null
  rscss/class-format:
    - true,
    - maxDepth: 3
  at-rule-no-unknown: null
  scss/at-rule-no-unknown: true
